language: julia
julia:
  - 1.1

branches:
  only:
   - master

env:
  global:
   - DOCUMENTER_DEBUG=true

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build(); Pkg.test("SeisMain"; coverage=true)'

